// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbmPQK8afy9sv4mvDt7JCdDrU9PXCe-zM',
    appId: '1:439540108756:web:a9a67e04ad86e8d1a95a41',
    messagingSenderId: '439540108756',
    projectId: 'dtd-packing',
    authDomain: 'dtd-packing.firebaseapp.com',
    storageBucket: 'dtd-packing.firebasestorage.app',
    measurementId: 'G-8GS5ZJ3D7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjZ7r8-IojQKUn5JhmFw4zEsxFK5azr-w',
    appId: '1:439540108756:android:250f633be7b69adea95a41',
    messagingSenderId: '439540108756',
    projectId: 'dtd-packing',
    storageBucket: 'dtd-packing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGt3IRi9z8ug3cihG38q7XI7I1HzWmIuI',
    appId: '1:439540108756:ios:0e2f57a138bdf350a95a41',
    messagingSenderId: '439540108756',
    projectId: 'dtd-packing',
    storageBucket: 'dtd-packing.firebasestorage.app',
    iosBundleId: 'com.example.zeroPacking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGt3IRi9z8ug3cihG38q7XI7I1HzWmIuI',
    appId: '1:439540108756:ios:0e2f57a138bdf350a95a41',
    messagingSenderId: '439540108756',
    projectId: 'dtd-packing',
    storageBucket: 'dtd-packing.firebasestorage.app',
    iosBundleId: 'com.example.zeroPacking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbmPQK8afy9sv4mvDt7JCdDrU9PXCe-zM',
    appId: '1:439540108756:web:762423cf3dfce308a95a41',
    messagingSenderId: '439540108756',
    projectId: 'dtd-packing',
    authDomain: 'dtd-packing.firebaseapp.com',
    storageBucket: 'dtd-packing.firebasestorage.app',
    measurementId: 'G-J94ETT0GTE',
  );
}
